apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: fatimahalkhamees-tawazun
  labels:
    app: tawazun
    name: fatimahalkhamees
spec:
  type: NodePort  
  selector:
    app:  tawazun
    service: tawazun-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31098