apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: fatimahalkhamees-tawazun
  labels:
    app: tawazun
    name: fatimahalkhamees
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage:  4Gi
  selector:
    matchLabels:
      app: tawazun