apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: fatimah-khamees-tawazun
  labels:
    app: tawazun
    name: fatimahalkhamees
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
