apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: fatimah-khamees-tawazun
  labels:
    app: tawazun
    name: fatimahalkhamees
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage:  5Gi
 