apiVersion: v1
kind: ResourceQuota
metadata:
 name: fatimahk-namespace
 namespace:  fatimahk-khamees-tawazun
spec:
 hard:
   requests.cpu: "2"
   requests.memory: 2Gi
   limits.cpu: "4"
   limits.memory: 4Gi
